### ISSUE TITLE
Performance comparison with zkCNN.

### ISSUE THREAD

**Issue by cstwhh** [ddkang/zkml#31]
Hi, thanks for your very practical work. Through a series of optimizations, the performance problem of zkml has been greatly solved.
We would like to learn more about how you compare the performance with zkCNN's work. The paper mentions "For zkCNN and pvCNN we estimate the proving time by scaling the largest model in the paper..., the proving time for the prior work is at least 10× higher than our method and up to 1,000× higher", we wanted to know more details and steps about how it was estimated. 
Thanks!

**Comment by ddkang** [comment]
We scaled the number of ReLU operations and the convolution sizes to match the smallest MobileNet in our paper.
